### ISSUE TITLE
ValueError: relative path can't be expressed as a file URI

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#139]
1. open .py file (with LSP server configured)
2. open .jpg file in another group
3. both files must be visible now
4. type something (but not space char) to trigger LSP diagnostics request for .py file.

```
ERROR: QueuesProcessingError: LSP: Python - relative path can't be expressed as a file URI
Traceback (most recent call last):
  File "F:\MySSDPrograms\cudatext\py\cuda_lsp\language.py", line 413, in process_queues
    self._on_lsp_msg(msg)
  File "F:\MySSDPrograms\cudatext\py\cuda_lsp\language.py", line 545, in _on_lsp_msg
    self.diagnostics_man.set_diagnostics(uri=msg.uri, diag_list=msg.diagnostics)
  File "F:\MySSDPrograms\cudatext\py\cuda_lsp\language.py", line 1121, in set_diagnostics
    if uri_to_path(uri) == uri_to_path(ed_uri(ed)):
  File "F:\MySSDPrograms\cudatext\py\cuda_lsp\util.py", line 86, in ed_uri
    return path_to_uri(fn)
  File "F:\MySSDPrograms\cudatext\py\cuda_lsp\util.py", line 79, in path_to_uri
    return pathlib.Path(path).as_uri()
  File "pathlib.py", line 748, in as_uri
ValueError: relative path can't be expressed as a file URI
```

added `print` to see what is coming to `path_to_uri`:

```python
def ed_uri(ed):
    fn = ed.get_filename()
    if fn:
        #return 'file://'+ed.get_filename()
        print("fn", fn)    
        return path_to_uri(fn)
    else:
        return 'file:///'+ed.get_prop(ct.PROP_TAB_TITLE).lstrip('*')
```

Output:
```
fn ?
```

as you can see, @Alexey-T , editor with .jpg file does not give the path of a file. just "?" text.

**Comment by Alexey-T** [comment]
It is documented behaviour- https://wiki.freepascal.org/CudaText_API#Editor.get_filename

call `ed.get_filename('*')`

**Comment by Alexey-T** [comment]
yes.

**Comment by Alexey-T** [comment]
I will apply it.
