### ISSUE TITLE
Traceback with any language-server

### ISSUE THREAD

**Issue by eltonfabricio10** [CudaText-addons/cuda_lsp#189]
```
Traceback (most recent call last):
  File "/home/eltonff/.config/cudatext/py/cuda_lsp/util.py", line 114, in d
    return f(*args, **vargs)
           ^^^^^^^^^^^^^^^^^
  File "/home/eltonff/.config/cudatext/py/cuda_lsp/lsp.py", line 398, in on_complete
    return doc.lang.on_complete(doc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eltonff/.config/cudatext/py/cuda_lsp/language.py", line 812, in on_complete
    id, pos = self._action_by_name(METHOD_COMPLETION, eddoc)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eltonff/.config/cudatext/py/cuda_lsp/language.py", line 721, in _action_by_name
    docpos = eddoc.get_docpos(caret)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eltonff/.config/cudatext/py/cuda_lsp/book.py", line 178, in get_docpos
    if self._lang.is_in_comment_or_string(self.ed, x1, y1):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eltonff/.config/cudatext/py/cuda_lsp/language.py", line 751, in is_in_comment_or_string
    return context in Language.disabled_contexts
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
ERROR: Exception in CudaText for on_complete: TypeError: argument of type 'NoneType' is not iterable
```

CudaText 1.198.0.0, linux-x86_64-qt5, fpc 3.2.3

[user.zip](https://github.com/CudaText-addons/cuda_lsp/files/12524963/user.zip)

**Comment by veksha** [comment]
@eltonfabricio10 , Hi. do you have `"disabled_contexts": null,` in `cuda_lsp.json`??
this is invalid value. value type must be a string, or delete it altogether. (it will be the default: `"disabled_contexts": "cs"`)

**Comment by eltonfabricio10** [comment]
Missed restarting Cud... Sorry!
