### ISSUE TITLE
Встроенная в плагин версия typing_extensions не работает с python 3.12.0

### ISSUE THREAD

**Issue by KDBalashevich** [CudaText-addons/cuda_lsp#191]
При попытке запуска lsp клиента консоли пояляется вот такая ошибка:
```
Traceback (most recent call last):
  File "/home/balkd/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/balkd/.config/cudatext/py/cuda_lsp/lsp.py", line 35, in <module>
    from .language import CompletionMan, Language
  File "/home/balkd/.config/cudatext/py/cuda_lsp/language.py", line 52, in <module>
    from .sansio_lsp_client import client as lsp
  File "/home/balkd/.config/cudatext/py/cuda_lsp/sansio_lsp_client/__init__.py", line 3, in <module>
    from .client import *
  File "/home/balkd/.config/cudatext/py/cuda_lsp/sansio_lsp_client/client.py", line 6, in <module>
    from pydantic import parse_obj_as, ValidationError
  File "/home/balkd/.config/cudatext/py/cuda_lsp/lsp_modules/pydantic/__init__.py", line 2, in <module>
    from . import dataclasses
  File "/home/balkd/.config/cudatext/py/cuda_lsp/lsp_modules/pydantic/dataclasses.py", line 41, in <module>
    from typing_extensions import dataclass_transform
  File "/home/balkd/.config/cudatext/py/cuda_lsp/lsp_modules/typing_extensions.py", line 1174, in <module>
    class TypeVar(typing.TypeVar, _DefaultMixin, _root=True):
TypeError: type 'typing.TypeVar' is not an acceptable base type
ERROR: Exception in CudaText for cuda_lsp.on_open: TypeError: type 'typing.TypeVar' is not an acceptable base type
```
При этом, если файл typing_extensions.py заменить на актуальный ([https://github.com/python/typing_extensions/releases/tag/4.8.0](https://github.com/python/typing_extensions/releases/tag/4.8.0)), то всё работает исправно.

Версия cudatext: 1.201.0.2 (linux-x86_64-gtk2)
Версия cuda_lsp: 2023.09.08
Версия Python: 3.12.0 (GCC 12.2.0 on linux)

**Comment by Alexey-T** [comment]
@veksha обновим модуль с указанной ссылки? есть время?

**Comment by Alexey-T** [comment]
заливаю обновление плагина с этим фиксом.
