### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#42]
```
Python 3.8.10
Init: cuda_lsp
LSP: starting server - Fortran; root: None
ERROR: QueuesProcessingError: LSP: Fortran - 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 388, in process_queues
    self._on_lsp_msg(msg)
  File "/home/user/.config/cudatext/py/cuda_lsp/language.py", line 427, in _on_lsp_msg
    items = msg.completion_list.items
AttributeError: 'NoneType' object has no attribute 'items'
```

- Install Fortran server https://wiki.freepascal.org/CudaText_plugins#LSP_server_for_Fortran
- Take test file but call autocompletion not like WIKI shows, but like char `|` shows
```
PROGRAM myprog
USE test_free, ONLY: scaled_vector
TYPE(scaled_vector) :: myvec
CALL |myv
END PROGRAM
```

@veksha's Git, branch autocomplete.cache.2

**Comment by Alexey-T** [comment]
same here (caret on 'PROGRAM')
```
PROGRAM myprog
USE test_free, ONLY: scaled_vector
TYPE(scaled_vector) :: myvec
CALL myv
END PR|OGRAM
```

**Comment by Alexey-T** [comment]
my fix in language.py, 

line 426 ` elif msgtype == events.Completion:`
```
        elif msgtype == events.Completion:
            if msg.completion_list:
                items = msg.completion_list.items
                pass;       LOG and print(f'got completion({len(items)}): {time.time():.3f} {msg.message_id} in {list(self.request_positions)}')
                reqpos = self.request_positions.pop(msg.message_id, None)
            else:
                items = None
            #print('msg.completion_list.isIncomplete:',msg.completion_list.isIncomplete)
            if items:
                if reqpos:
                    try:
                        compl = CompletionMan(carets=reqpos.carets, h_ed=reqpos.h_ed)
                        #print("using fresh results.","items:",len(items)," incomplete:",msg.completion_list.isIncomplete)
                        self._last_complete = compl.show_complete(msg.message_id, items, msg.completion_list.isIncomplete)
                    except AssertionError as e:
                        print("NOTE:",e)
            else:
                msg_status(f'{LOG_NAME}: {self.lang_str}: Completion - no info')
```

**Comment by Alexey-T** [comment]
@veksha, is my fix ok?

**Comment by veksha** [comment]
We need to check why it comes "None". maybe we can find and fix some error instead of just hiding it.

**Comment by Alexey-T** [comment]
please search for it (I don't know code)

**Comment by veksha** [comment]
> Git, branch autocomplete.cache.2

I see it happens on "main" branch too.

**Comment by veksha** [comment]
I checked. Yes, your fix is ok.
if there are zero results: this lsp-server returns "null" result,
others lsp-servers send object with an empty list as a result.

according to LSP spec null result is allowed. so your fix is fine.

**Comment by veksha** [comment]
> Do you plan to refactor that branch, as you said?

yes, I think cache changes can be moved to a dedicated function at least.

**Comment by veksha** [comment]
> pls merge my fix.

done
