### ISSUE TITLE
Java LSP issues

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_lsp#95]
this works ok: `"cmd_windows": ["C:\\Java\\jLSP.cmd", "."]`
but if parameter to cmd file were not provided we got error.

`"cmd_windows": ["C:\\Java\\jLSP.cmd"]`

Console:
```
ReadLoopError: LSP: Java - [Errno 10] No child processes
ERROR: QueuesProcessingError: LSP: Java - not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "F:\MySSDPrograms\cudatext\py\cuda_lsp\language.py", line 396, in process_queues
    events = self.client.recv(data, errors=errors)
  File "F:\MySSDPrograms\cudatext\py\cuda_lsp\sansio_lsp_client\client.py", line 443, in recv
    messages = list(_parse_messages(self._recv_buf))
  File "F:\MySSDPrograms\cudatext\py\cuda_lsp\sansio_lsp_client\io_handler.py", line 173, in _parse_messages
    parsed = _parse_one_message(response_buf)
  File "F:\MySSDPrograms\cudatext\py\cuda_lsp\sansio_lsp_client\io_handler.py", line 120, in _parse_one_message
    key, value = header_line.decode("ascii").split(": ", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

LSP panel stdout:
```
Error: No cache directory was provided.
```

**Comment by veksha** [comment]
after last changes it is fixed:

Console:
```
ReadLoopError: LSP: Java - [Errno 10] No child processes
```

LSP panel:
```
Error: No cache directory was provided.

  Usage: jLSP.cmd WorkspaceDirectory FileDirectory
Example: jLSP.cmd "$wdd" "$fdd"

```

**Comment by Alexey-T** [comment]
good,
